slack_hook_port: 9898
bot_username: "slackbot"
username_prefix: "slack_"

# Optional
slack_master_token: "abc-123-def"

homeserver:
  url: http://localhost:8008
  server_name: my.server

# Optional
tls:
  key_file: /path/to/tls.key
  crt_file: /path/to/tls.crt

rooms:
  - slack_channel_id: "QWERTYUIOP"
    slack_api_token: "ABC123"
    matrix_room_id: "!ZXC987:matrix.org"
    webhook_url: "https://hooks.slack.com/services/ABC/DEF/123"
