type: object
required: ["homeserver", "slack_hook_port", "bot_username", "username_prefix"]
properties:
  homeserver:
    type: object
    required: ["server_name", "url"]
    properties:
      server_name:
        type: string
      url:
        type: string
  tls:
    type: object
    required: ["key_file", "crt_file"]
    properties:
      key_file:
        type: string
      crt_file:
        type: string
  slack_hook_port:
    type: integer
  rooms:
    type: array
    items:
      type: object
      required: ["slack_channel_id", "slack_api_token", "webhook_url"]
      properties:
        slack_channel_id:
          type: string
        slack_api_token:
          type: string
        matrix_room_id:
          type: string
        matrix_room_ids:
          type: array
          items:
            type: string
        webhook_url:
          type: string
  bot_username:
    type: string
  username_prefix:
    type: string
  matrix_admin_room:
    type: string
  slack_master_token:
    # Required for some functionality, like sending images from Slack to Matrix.
    # Bridge gracefully degrades if no slack_master_token is specified.
    type: string
